# Copyright 2023 Circle Internet Financial, LTD.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

scan:
  scanners:
    - license
license:
  confidencelevel: "0.9"
  # License classifications are taken from the Circle Open Source Standard
  # Any license not specifically listed will be classified as `UNKNOWN` vulnerability level
  unencumbered: []
  forbidden: []
  permissive: []
  # These are not actual licenses, but rather are artifacts of parsing non-standard license strings
  # contained in POM files.
  ignored:
    - "2.0"
    - With Classpath Exception
  # Restricted translates to `HIGH` vulnerability level
  # These licenses are generally unacceptable to use in any context.
  restricted:
    - AGPL-1.0 # AGPL 1.0
    - AGPL-1.0-or-later # AGPL 1.0 or later
    - AGPL-3.0 # AGPL 3.0
    - AGPL-3.0-or-later # AGPL 3.0 or later
    - SSPL-1.0 # Server Side Public License
    - OSL-1.0 # Open Software License 1.0
    - OSL-1.1 # Open Software License 1.1
    - OSL-2.0 # Open Software License 2.0
    - OSL-2.1 # Open Software License 2.1
    - OSL-3.0 # Open Software License 3.0
    - NPOSL-3.0 # Non-Profit Open Software License 3.0
    - AFL-1.1 # Academic Free License v1.1
    - AFL-1.2 # Academic Free License v1.2
    - AFL-2.0 # Academic Free License v2.0
    - AFL-2.1 # Academic Free License v2.1
    - AFL-3.0 # Academic Free License v3.0
    - APSL-1.0 # Apple Public Source License 1.0
    - APSL-1.1 # Apple Public Source License 1.1
    - APSL-1.2 # Apple Public Source License 1.2
    - APSL-2.0 # Apple Public Source License 2.0
    - RPSL-1.0 # RealNetworks Public Source License v1.0
    - RPL-1.1 # Reciprocal Public License 1.1
    - RPL-1.5 # Reciprocal Public License 1.5
    - Hippocratic-2.1 # Hippocratic License 2.1
    - Elastic-2.0 # Elastic License 2.0
    - BUSL-1.1 # Business Source License 1.1
    - PolyForm-Noncommercial-1.0.0 # PolyForm Noncommercial License 1.0.0
    - PolyForm-Small-Business-1.0.0 # PolyForm Small Business License 1.0.0
  # Reciprocal translates to `MEDIUM` vulnerability level
  # These licenses may be acceptable depending on context.
  reciprocal:
    - GPL-2.0 # GNU General Public License v2.0 only
    - The GNU General Public License (GPL), Version 2 # GNU General Public License v2.0 only
    - GNU General Public License Version 2 # GNU General Public License v2.0 only
    - GPL-2.0+ # GNU General Public License v2.0 or later
    - GPL2 w/ CPE # GNU General Public License v2.0 with classpath exception
    - GPL-2.0-or-later # GNU General Public License v2.0 or later
    - GPL-3.0 # GNU General Public License v2.0 only
    - GPL-3.0+ # GNU General Public License v2.0 or later
    - GPL-3.0-or-later # GNU General Public License v3.0 or later
    - LGPL-2.1 # GNU Lesser General Public License v2.1
    - LGPL-2.1+ # GNU Lesser General Public License v2.1 or later
    - GNU Lesser General Public License Version 2.1 # GNU Lesser General Public License v2.1
    - LGPL-2.1-or-later # GNU Lesser General Public License v2.1 or later
    - LGPL-3.0 # GNU Lesser General Public License v3.0
    - LGPL-3.0+ # GNU Lesser General Public License v3.0 or later
    - LGPL-3.0-or-later # GNU Lesser General Public License v3.0 or later
    - MPL-1.1 # Mozilla Public License 1.1
    - MPL 1.1 # Mozilla Public License 1.1
    - MPL-2.0 # Mozilla Public License 2.0
    - MPL-2.0-no-copyleft-exception # Mozilla Public License 2.0 (no copyleft exception)
    - CDDL-1.0 # Common Development and Distribution License 1.0
    - CDDL-1.1 # Common Development and Distribution License 1.1
    - CDDL + GPLv2 with classpath exception # CDDL and GPL-2 w/claspath exception
    - CPL-1.0 # Common Public License 1.0
    - IPL-1.0 # IBM Public License v1.0
    - EPL-1.0 # Eclipse Public License 1.0
    - Eclipse Public License - Version 1.0 # Eclipse Public License 1.0
    - Eclipse Public License - v 1.0 # Eclipse Public License 1.0
    - EPL-2.0 # Eclipse Public License 2.0
    - EPL 2.0 # Eclipse Public License 2.0
    - Eclipse Public License - v 2.0 # Eclipse Public License 2.0
    - Apache-1.0 # Apache License 1.0
    - Apache License # Apache License
    - CC-BY-SA-1.0 # Creative Commons Attribution Share Alike 1.0 Generic
    - CC-BY-SA-2.0 # Creative Commons Attribution Share Alike 2.0 Generic
  # Notice translates to `LOW` vulnerability level.
  # These licenses are generally acceptable to use
  # This list includes licenses from the [Blue Oak Council](https://blueoakcouncil.org/) list.
  notice:
    - BSD-1-Clause # BSD 1-Clause License
    - BSD-2-Clause # BSD 2-Clause "Simplified" License
    - BSD 2-Clause # BSD 2-Clause "Simplified" License
    - BSD-3-Clause # BSD 3-Clause "New" or "Revised" License
    - The BSD 3-Clause License # BSD 3-Clause "New" or "Revised" License
    - The New BSD License # BSD 3-Clause "New" or "Revised" License
    - Modified BSD # BSD 3-Clause "New" or "Revised" License (String used in https://github.com/eclipse-ee4j/jersey/blob/2.x/core-server/pom.xml to describe https://asm.ow2.io/license.html)
    - Revised BSD # BSD 3-Clause "New" or "Revised" License
    - MIT # MIT License
    - MIT License # MIT License
    - MIT license # MIT License
    - The MIT License # MIT License
    - The MIT License (MIT) # MIT License
    - MIT-0 # MIT No Attribution
    - Apache-1.1 # Apache License 1.1
    - Apache Software License, Version 1.1 # Apache License 1.1
    - Apache-2.0 # Apache License 2.0
    - Apache License 2.0 # Apache License 2.0
    - The Apache License, Version 2.0 # Apache License 2.0
    - Apache License, Version 2.0 # Apache License 2.0
    - Apache License, version 2.0 # Apache License 2.0
    - The Apache Software License, Version 2.0 # Apache License 2.0
    - Apache Software License - Version 2.0 # Apache License 2.0
    - Artistic-1.0 # Artistic License 1.0
    - Artistic-2.0 # Artistic License 2.0
    - PHP-3.0 # PHP License v3.0
    - PHP-3.01 # PHP License v3.01
    - PSF-2.0 # Python Software Foundation License 2.0
    - Zlib # zlib License
    - zlib-acknowledgement # zlib/libpng License with Acknowledgement
    - BSL-1.0 # Boost Software License 1.0
    - OpenSSL # OpenSSL License
    - WTFPL # Do What The F*ck You Want To Public License
    - CC0-1.0 # Creative Commons Zero v1.0 Universal
    - CC-PDDC # Creative Commons Public Domain Dedication and Certification
    - CC-BY-1.0 # Creative Commons Attribution 1.0 Generic
    - CC-BY-2.0 # Creative Commons Attribution 2.0 Generic
    - CC-BY-2.5 # Creative Commons Attribution 2.5 Generic
    - CC-BY-3.0 # Creative Commons Attribution 3.0 Unported
    - CC-BY-4.0 # Creative Commons Attribution 4.0 International
    - Unlicense # The Unlicense
    - ISC # ISC License
    # Blue Oak "Model" licenses
    - BlueOak-1.0.0 # Blue Oak Model License 1.0.0
    # Blue Oak "Gold" licenses
    - BSD-2-Clause-Patent # BSD-2-Clause Plus Patent License
    # Blue Oak "Silver" licenses
    - ADSL # Amazon Digital Services License
    - Apache-2.0 # Apache License 2.0
    - APAFML # Adobe Postscript AFM License
    - BSD-1-Clause # BSD 1-Clause License
    - BSD-2-Clause # BSD 2-Clause "Simplified" License
    - BSD-2-Clause-FreeBSD # BSD 2-Clause FreeBSD License
    - BSD-2-Clause-NetBSD # BSD 2-Clause NetBSD License
    - BSD-2-Clause-Views # BSD 2-Clause with Views Sentence
    - BSL-1.0 # Boost Software License 1.0
    - DSDP # DSDP License
    - ECL-1.0 # Educational Community License v1.0
    - ECL-2.0 # Educational Community License v2.0
    - ImageMagick # ImageMagick License
    - ISC # ISC License
    - Linux-OpenIB # Linux Kernel Variant of OpenIB.org license
    - MIT # MIT License
    - MIT-Modern-Variant # MIT License Modern Variant
    - MS-PL # Microsoft Public License
    - MulanPSL-1.0 # Mulan Permissive Software License, Version 1
    - Mup # Mup License
    - PostgreSQL # PostgreSQL License
    - Spencer-99 # Spencer License 99
    - UPL-1.0 # Universal Permissive License v1.0
    - Xerox # Xerox License
    # Blue Oak "Bronze" licenses
    - 0BSD # BSD Zero Clause License
    - AFL-1.1 # Academic Free License v1.1
    - AFL-1.2 # Academic Free License v1.2
    - AFL-2.0 # Academic Free License v2.0
    - AFL-2.1 # Academic Free License v2.1
    - AFL-3.0 # Academic Free License v3.0
    - AMDPLPA # AMD's plpa_map.c License
    - AML # Apple MIT License
    - AMPAS # Academy of Motion Picture Arts and Sciences BSD
    - ANTLR-PD # ANTLR Software Rights Notice
    - ANTLR-PD-fallback # ANTLR Software Rights Notice with license fallback
    - Apache-1.0 # Apache License 1.0
    - Apache-1.1 # Apache License 1.1
    - Artistic-2.0 # Artistic License 2.0
    - Bahyph # Bahyph License
    - Barr # Barr License
    - BSD-3-Clause # BSD 3-Clause "New" or "Revised" License
    - BSD-3-Clause-Attribution # BSD with attribution
    - BSD-3-Clause-Clear # BSD 3-Clause Clear License
    - BSD-3-Clause-LBNL # Lawrence Berkeley National Labs BSD variant license
    - BSD-3-Clause-Modification # BSD 3-Clause Modification
    - BSD-3-Clause-No-Nuclear-License-2014 # BSD 3-Clause No Nuclear License 2014
    - BSD-3-Clause-No-Nuclear-Warranty # BSD 3-Clause No Nuclear Warranty
    - BSD-3-Clause-Open-MPI # BSD 3-Clause Open MPI Variant
    - BSD-4-Clause # BSD 4-Clause "Original" or "Old" License
    - BSD-4-Clause-Shortened # BSD 4-Clause Shortened
    - BSD-4-Clause-UC # BSD-4-Clause (University of California-Specific)
    - BSD-Source-Code # BSD Source Code Attribution
    - bzip2-1.0.5 # bzip2 and libbzip2 License v1.0.5
    - bzip2-1.0.6 # bzip2 and libbzip2 License v1.0.6
    - CC0-1.0 # Creative Commons Zero v1.0 Universal
    - CNRI-Jython # CNRI Jython License
    - CNRI-Python # CNRI Python License
    - CNRI-Python-GPL-Compatible # CNRI Python Open Source GPL Compatible License Agreement
    - Cube # Cube License
    - curl # curl License
    - eGenix # eGenix.com Public License 1.1.0
    - Entessa # Entessa Public License v1.0
    - FTL # Freetype Project License
    - HTMLTIDY # HTML Tidy License
    - IBM-pibs # IBM PowerPC Initialization and Boot Software
    - ICU # ICU License
    - Info-ZIP # Info-ZIP License
    - Intel # Intel Open Source License
    - JasPer-2.0 # JasPer License
    - Libpng # libpng License
    - libpng-2.0 # PNG Reference Library version 2
    - libtiff # libtiff License
    - LPPL-1.3c # LaTeX Project Public License v1.3c
    - MIT-0 # MIT No Attribution
    - MIT-advertising # Enlightenment License (e16)
    - MIT-open-group # MIT Open Group Variant
    - MIT-CMU # CMU License
    - MIT-enna # enna License
    - MIT-feh # feh License
    - MITNFA # MIT +no-false-attribs license
    - MTLL # Matrix Template Library License
    - MulanPSL-2.0 # Mulan Permissive Software License, Version 2
    - Multics # Multics License
    - Naumen # Naumen Public License
    - NCSA # University of Illinois/NCSA Open Source License
    - Net-SNMP # Net-SNMP License
    - NetCDF # NetCDF license
    - NTP # NTP License
    - OLDAP-2.0 # Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)
    - OLDAP-2.0.1 # Open LDAP Public License v2.0.1
    - OLDAP-2.1 # Open LDAP Public License v2.1
    - OLDAP-2.2 # Open LDAP Public License v2.2
    - OLDAP-2.2.1 # Open LDAP Public License v2.2.1
    - OLDAP-2.2.2 # Open LDAP Public License 2.2.2
    - OLDAP-2.3 # Open LDAP Public License v2.3
    - OLDAP-2.4 # Open LDAP Public License v2.4
    - OLDAP-2.5 # Open LDAP Public License v2.5
    - OLDAP-2.6 # Open LDAP Public License v2.6
    - OLDAP-2.7 # Open LDAP Public License v2.7
    - OLDAP-2.8 # Open LDAP Public License v2.8
    - OML # Open Market License
    - OpenSSL # OpenSSL License
    - PHP-3.0 # PHP License v3.0
    - PHP-3.01 # PHP License v3.01
    - Plexus # Plexus Classworlds License
    - PSF-2.0 # Python Software Foundation License 2.0
    - Python-2.0 # Python License 2.0
    - Ruby # Ruby License
    - Saxpath # Saxpath License
    - SGI-B-2.0 # SGI Free Software License B v2.0
    - SMLNJ # Standard ML of New Jersey License
    - SWL # Scheme Widget Library (SWL) Software License Agreement
    - TCL # TCL/TK License
    - TCP-wrappers # TCP Wrappers License
    - Unicode-DFS-2015 # Unicode License Agreement - Data Files and Software (2015)
    - Unicode-DFS-2016 # Unicode License Agreement - Data Files and Software (2016)
    - Unlicense # The Unlicense
    - VSL-1.0 # Vovida Software License v1.0
    - W3C # W3C Software Notice and License (2002-12-31)
    - X11 # X11 License
    - XFree86-1.1 # XFree86 License 1.1
    - Xnet # X.Net License
    - xpp # XPP License
    - Zlib # zlib License
    - zlib-acknowledgement # zlib/libpng License with Acknowledgement
    - ZPL-2.0 # Zope Public License 2.0
    - ZPL-2.1 # Zope Public License 2.1
    # Blue Oak "Lead" licenses
    - AAL # Attribution Assurance License
    - Adobe-2006 # Adobe Systems Incorporated Source Code License Agreement
    - Afmparse # Afmparse License
    - Artistic-1.0 # Artistic License 1.0
    - Artistic-1.0-cl8 # Artistic License 1.0 w/clause 8
    - Artistic-1.0-Perl # Artistic License 1.0 (Perl)
    - Beerware # Beerware License
    - blessing # SQLite Blessing
    - Borceux # Borceux license
    - CECILL-B # CeCILL-B Free Software License Agreement
    - ClArtistic # Clarified Artistic License
    - Condor-1.1 # Condor Public License v1.1
    - Crossword # Crossword License
    - CrystalStacker # CrystalStacker License
    - diffmark # diffmark license
    - DOC # DOC License
    - EFL-1.0 # Eiffel Forum License v1.0
    - EFL-2.0 # Eiffel Forum License v2.0
    - Fair # Fair License
    - FSFUL # FSF Unlimited License
    - FSFULLR # FSF Unlimited License (with License Retention)
    - Giftware # Giftware License
    - HPND # Historical Permission Notice and Disclaimer
    - IJG # Independent JPEG Group License
    - Leptonica # Leptonica License
    - LPL-1.0 # Lucent Public License Version 1.0
    - LPL-1.02 # Lucent Public License v1.02
    - MirOS # MirOS License
    - mpich2 # mpich2 License
    - NASA-1.3 # NASA Open Source Agreement 1.3
    - NBPL-1.0 # Net Boolean Public License v1
    - Newsletr # Newsletr License
    - NLPL # No Limit Public License
    - NRL # NRL License
    - OGTSL # Open Group Test Suite License
    - OLDAP-1.1 # Open LDAP Public License v1.1
    - OLDAP-1.2 # Open LDAP Public License v1.2
    - OLDAP-1.3 # Open LDAP Public License v1.3
    - OLDAP-1.4 # Open LDAP Public License v1.4
    - psutils # psutils License
    - Qhull # Qhull License
    - Rdisc # Rdisc License
    - RSA-MD # RSA Message-Digest License
    - Spencer-86 # Spencer License 86
    - Spencer-94 # Spencer License 94
    - TU-Berlin-1.0 # Technische Universitaet Berlin License 1.0
    - TU-Berlin-2.0 # Technische Universitaet Berlin License 2.0
    - Vim # Vim License
    - W3C-19980720 # W3C Software Notice and License (1998-07-20)
    - W3C-20150513 # W3C Software Notice and Document License (2015-05-13)
    - Wsuipa # Wsuipa License
    - WTFPL # Do What The F*ck You Want To Public License
    - xinetd # xinetd License
    - Zed # Zed License
    - Zend-2.0 # Zend License v2.0
    - ZPL-1.1 # Zope Public License 1.1
